### ISSUE TITLE
Test results do not appear in TeamCity

### ISSUE THREAD

**Issue by workmaster2n** [jasmine/jasmine-gem#239]
I run `rake jasmine:ci` as part of my build process and can inspect the logs to see the tests are successfully passing, but the tests aren't appearing in the test result page for TeamCity.

TeamCity: 8.1.5
jasmine: 2.2.0

**Comment by slackersoft** [comment]
The `jasmine:ci` rake task just prints the results to the console by default. I'm not sure what TeamCity needs to have happen in order to understand that they are test results.

You may need to find or create a [custom reporter](http://jasmine.github.io/2.0/ruby_gem.html#section-Custom_Formatters) in order to accomplish this.

**Comment by workmaster2n** [comment]
Cool, thanks for that info. I'll see if I can't figure out how to capture that output and turn it into something TeamCity understands.

**Comment by slackersoft** [comment]
I'm going close this issue, since it sounds like jasmine itself is functioning as expected.

You might also take a look at the [TeamCity plugins](https://confluence.jetbrains.com/display/TW/TeamCity+Plugins), it looks like they point to a couple things for jasmine.
