### ISSUE TITLE
Errno::EADDRINUSE: Address already in use - bind(2) for "0.0.0.0" port 49881

### ISSUE THREAD

**Issue by snoblenet** [jasmine/jasmine-gem#267]
Should I be worried about this?

````
$ bundle exec rake jasmine:ci
Puma starting in single mode...
* Version 3.4.0 (ruby 2.3.1-p112), codename: Owl Bowl Brawl
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:49881
Use Ctrl-C to stop
Waiting for jasmine server on 49881...
jasmine server started
.....
5 specs, 0 failures
Puma starting in single mode...
* Version 3.4.0 (ruby 2.3.1-p112), codename: Owl Bowl Brawl
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:49881
rake aborted!
Errno::EADDRINUSE: Address already in use - bind(2) for "0.0.0.0" port 49881
````

I'm running the `ci` version because (a) it's handy if I'm in the Terminal already, and (b) I wanted to see what Jenkins will see when I eventually push up our first branch to incorporate Jasmine. I'm hoping the matters in the stack trace above will not bother Jenkins. It looks like the rake task is trying to start the server twice on the same port. Is that right? Can it be stopped? Thanks.

**Comment by slackersoft** [comment]
Typically we've seen this when the Jasmine rake tasks are included twice. If you're using rails, you should no longer need anything specific in your `Rakefile` to bring in Jasmine's tasks. I believe newer versions of Jasmine should also print a message if it thinks the rake tasks are included more than once.

Closing this, since it seems like a rake task issue. I'm happy to look into this more if that doesn't fix it. Thanks for using Jasmine!
