### ISSUE TITLE
Too optimistic jasmine-core dependency

### ISSUE THREAD

**Issue by himdel** [jasmine/jasmine-gem#271]
Jasmine gem 2.4.1 depends on jasmine-core ~> 2.4 which means it's using 2.5.0 now. The correct dependency would be ~> 2.4.0.

The same problem is present in master..

**Comment by slackersoft** [comment]
Are you seeing incompatibilities when spanning versions like this? The intent with the versioning has been more to ensure that your Jasmine-Core version updates when you upgrade your Jasmine gem dependency.

Unfortunately, due to how these releases work, we can't change the dependency for the already released 2.4.1, but we can look into this again and see about locking the versions together more.

**Comment by himdel** [comment]
Yes, the main issue is that `jasmine-core` 2.5.0 no longer works in any version of `phantomjs` there's a gem for :).

Given that, I think it may even make sense to do a `2.4.2` release that just forces jasmine-core to 2.4.. but up to you, we've since [fixed](https://github.com/ManageIQ/manageiq/pull/10898) by explicitly depending on jasmine-core as well..

**Comment by slackersoft** [comment]
Jasmine 2.5.1 should fix the issues with phantomjs that popped up in 2.5.0. For right now, we don't have any plans to change the version interdependencies we have right now.

Closing this. Thanks for using Jasmine!

**Comment by himdel** [comment]
Allright, @slackersoft, thanks anyway :) As long as you **know** that when jasmine 2.6.0 comes out, jasmine-gem 2.5.0 will start bringing that one in, I'm OK with that, we'll just keep the explicit `jasmine-core` dependency then.
