### ISSUE TITLE
Make "Spec List" default

### ISSUE THREAD

**Issue by ThomasSzabo** [jasmine/jasmine-gem#278]
When (re-)loading the "Jasmine suite" page from localhost, I would like to see the "Spec List" instead of "Failures". Is there an option for this?

**Comment by slackersoft** [comment]
The spec list view will be shown if your suite does not have any failures. There isn't an option to make it the default view when there are failures in your tests, since the assumption is that you'll want to fix the errors.

I don't think this is functionality that we're looking to change, so I'm going to close this issue. Thanks for using Jasmine!
