### ISSUE TITLE
set seed via configuration

### ISSUE THREAD

**Issue by ToadJamb** [jasmine/jasmine-gem#291]
I can set random to true in my yaml file as follows:

```
random: true
```

But I can not find any way to set the seed and in perusing the source code, it appears that seed is not exposed via either the yaml interface or the configuration block in the ruby helper file.

**Comment by slackersoft** [comment]
Setting a specific seed value _should_ just be a temporary thing while debugging an issue you've discovered via random test ordering. If you find yourself needing a hard-coded seed for longer, then you're not really running random ordering of tests anymore, so we opted to provide access to this via the rake task execution for one-off runs in order to make it harder to accidentally commit a configuration that would fix the order.

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
We haven't heard anything else on this issue in a while and I'm not totally convinced on the use case. I'd be happy to talk more about the requested functionality, but I'm going to close this issue for now.

Thanks for using Jasmine!
